import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AudioPlayer } from "../components/AudioPlayer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SOUNDCLOUT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">SOUNDCLOUT</a>
        </h1>
        <h2>gang shit</h2>
        <AudioPlayer />
      </main>
    </div>
  );
}
